import type { SimulationConfig } from '../types';
import { createUWBPHYLayer, createFiRaLayer } from '../layers/uwb';

export const uwbRanging: SimulationConfig = {
	protocolId: 'uwb',
	title: 'UWB Ranging — BLE bootstrap → DS-TWR → distance',
	description:
		'The five beats every consumer UWB session walks: BLE advertise → BLE GATT pairing + STS_KEY transport → UWB Poll → UWB Response → UWB Final → distance. Same flow under AirTag Precision Finding, BMW Digital Key, Aqara U400 hands-free unlock, and (from Feb 2026) Aliro 1.0 for everyone else.',
	tier: 'client',
	actors: [
		{ id: 'phone', label: 'iPhone (Initiator)', icon: 'device', position: 'left' },
		{ id: 'anchor', label: 'Car / Lock / AirTag (Responder)', icon: 'server', position: 'right' }
	],
	userInputs: [
		{
			id: 'channel',
			label: 'UWB channel',
			type: 'select',
			defaultValue: 'Channel 9 (7987.2 MHz)',
			options: ['Channel 5 (6489.6 MHz, universal)', 'Channel 9 (7987.2 MHz, restricted in Japan)']
		},
		{
			id: 'mode',
			label: 'Ranging mode',
			type: 'select',
			defaultValue: 'DS-TWR (production)',
			options: ['DS-TWR (production)', 'SS-TWR (legacy)', 'TDoA (infrastructure RTLS)']
		},
		{
			id: 'sts',
			label: 'STS cipher suite',
			type: 'select',
			defaultValue: 'STS_KEY 128-bit (4z secure)',
			options: ['STS_KEY 128-bit (4z secure)', 'No STS (4a legacy — insecure)']
		}
	],
	steps: [
		{
			id: 'ble-adv',
			label: 'BLE advertising — anchor broadcasts service UUID',
			description:
				"Every consumer UWB session opens over BLE. The anchor (car, lock, AirTag) broadcasts an `ADV_NONCONN_IND` on advertising channels 37/38/39 carrying the application's service UUID (Apple Find My, CCC Digital Key, Aliro). The phone scans those channels; UWB is not yet powered.",
			fromActor: 'anchor',
			toActor: 'phone',
			duration: 800,
			highlight: ['Channel', 'Mode'],
			data: 'BLE ADV_NONCONN_IND: AppleFindMy service data, ephemeral pubkey',
			layers: [
				createUWBPHYLayer({
					channel: '(BLE 2.402 GHz — UWB radio off)',
					mode: 'BLE 1M PHY, advertising',
					shr: '(BLE preamble + Access Address 0x8E89BED6)',
					phr: '(BLE PDU header)',
					psdu: 'AdvA + Service Data (FindMy ephemeral pubkey)',
					sts: '(none — BLE bootstrap)'
				})
			]
		},
		{
			id: 'ble-auth',
			label: 'BLE GATT pairing + STS_KEY transport',
			description:
				"The phone connects, GATT-discovers the ranging service, and runs the application-specific authentication (SPAKE2+/PAKE for {{ccc-digital-key|CCC Digital Key}}; Apple's proprietary handshake for Find My; ECDSA mutual auth for {{aliro|Aliro}}). Once authenticated, the phone and the anchor exchange the **STS_KEY** (128-bit AES key for this ranging session) and the ranging schedule over the BLE encrypted channel.",
			fromActor: 'phone',
			toActor: 'anchor',
			duration: 1200,
			highlight: ['Channel', 'Mode'],
			data: 'GATT APDU exchange: SPAKE2+ handshake → STS_KEY = derived 128-bit key',
			layers: [
				createUWBPHYLayer({
					channel: '(BLE 2.402 GHz — UWB still off)',
					mode: 'BLE 2M PHY, connection',
					shr: '(BLE LL data PDU)',
					phr: '(L2CAP + ATT framing)',
					psdu: 'PAKE / APDU exchange → STS_KEY derivation',
					sts: '(none — derived over BLE, used for UWB next)'
				})
			]
		},
		{
			id: 'uwb-poll',
			label: 'UWB Poll — RFRAME with STS, initiator timestamps t1',
			description:
				'The phone fires up its UWB radio. It transmits a **Poll** RFRAME on Channel 9 (7987.2 MHz, 499.2 MHz BW) at 6.81 Mbps. The frame carries a 32-chip STS segment generated by `AES-128-CTR(STS_KEY, nonce || 0)`. At the moment the SFD is on the air, the phone records `t1 = TX timestamp` (resolution ~15 ps).',
			fromActor: 'phone',
			toActor: 'anchor',
			duration: 1000,
			highlight: ['Channel', 'PHR', 'STS', 'Frame Type', 'Timestamps'],
			layers: [
				createUWBPHYLayer({
					channel: 'Ch 9 — 7987.2 MHz, 499.2 MHz BW',
					mode: 'BPRF 64 MHz, 6.81 Mbps',
					shr: '64 sync symbols + 8-symbol SFD',
					phr: 'len=12, RFRAME=1, rate=01 (6.81 Mbps)',
					psdu: 'Ranging seq=0, peer addr=0x1234',
					sts: '32 chips × AES-128-CTR(STS_KEY, nonce || 0)'
				}),
				createFiRaLayer({
					sessionId: '0x0001A2B3',
					round: 0x002a,
					frameType: 'Poll (00)',
					timestamps: 't1 = 0x000000123456 (TX timestamp)',
					peer: 'Init=0x4321 → Resp=0x1234'
				})
			]
		},
		{
			id: 'uwb-response',
			label: 'UWB Response — responder echoes t2, t3',
			description:
				"The anchor's UWB receiver detects the SFD's first-path arrival and records `t2 = RX timestamp`. After a deliberate `T_reply1` processing delay (~200 µs typical), the anchor transmits a **Response** RFRAME with its own STS segment, carrying t2 and t3 in the payload. The phone's UWB receiver records `t4 = RX timestamp` when this frame arrives.",
			fromActor: 'anchor',
			toActor: 'phone',
			duration: 1000,
			highlight: ['STS', 'Frame Type', 'Timestamps'],
			layers: [
				createUWBPHYLayer({
					channel: 'Ch 9 — 7987.2 MHz, 499.2 MHz BW',
					mode: 'BPRF 64 MHz, 6.81 Mbps',
					shr: '64 sync symbols + 8-symbol SFD',
					phr: 'len=24, RFRAME=1, rate=01',
					psdu: 'Ranging seq=1; t2=0x..56789A, t3=0x..56ABCD',
					sts: '32 chips × AES-128-CTR(STS_KEY, nonce || 1)'
				}),
				createFiRaLayer({
					sessionId: '0x0001A2B3',
					round: 0x002a,
					frameType: 'Response (01)',
					timestamps: 't2 = RX of Poll, t3 = TX of Response (carried in payload)',
					peer: 'Resp=0x1234 → Init=0x4321'
				})
			]
		},
		{
			id: 'uwb-final',
			label: 'UWB Final — initiator sends t1, t4, t5',
			description:
				'After its own `T_reply2` processing delay, the phone transmits a **Final** RFRAME carrying t1, t4, and its new TX timestamp t5. The anchor records `t6 = RX timestamp`. Both sides now have all six timestamps and can compute the time-of-flight via the DS-TWR cross-product.',
			fromActor: 'phone',
			toActor: 'anchor',
			duration: 1000,
			highlight: ['STS', 'Frame Type', 'Timestamps'],
			layers: [
				createUWBPHYLayer({
					channel: 'Ch 9 — 7987.2 MHz, 499.2 MHz BW',
					mode: 'BPRF 64 MHz, 6.81 Mbps',
					shr: '64 sync symbols + 8-symbol SFD',
					phr: 'len=32, RFRAME=1, rate=01',
					psdu: 'Ranging seq=2; t1, t4, t5 (carried in payload)',
					sts: '32 chips × AES-128-CTR(STS_KEY, nonce || 2)'
				}),
				createFiRaLayer({
					sessionId: '0x0001A2B3',
					round: 0x002a,
					frameType: 'Final (02)',
					timestamps: 't1, t4, t5 carried in Final payload',
					peer: 'Init=0x4321 → Resp=0x1234'
				})
			]
		},
		{
			id: 'compute-tof',
			label: 'Compute ToF — DS-TWR cross-product cancels clock drift',
			description:
				'The anchor (or phone, in some implementations) plugs all six timestamps into the cross-product:\n\n`ToF = (T_round1 · T_round2 − T_reply1 · T_reply2) / (T_round1 + T_round2 + T_reply1 + T_reply2)`\n\nwhere `T_round1 = t4−t1`, `T_reply1 = t3−t2`, `T_round2 = t6−t3`, `T_reply2 = t5−t4`. The cross-product cancels relative clock drift to first order — DS-TWR is insensitive to 20 ppm crystal offsets, where SS-TWR would yield ~1.2 m of bias under the same conditions. Multiply ToF by `c ≈ 0.299792458 m/ns` to get distance.',
			fromActor: 'anchor',
			toActor: 'phone',
			duration: 800,
			highlight: ['Timestamps'],
			data: 'd = ToF × c = 4.7 ns × 0.299792458 m/ns ≈ 1.41 m',
			layers: [
				createFiRaLayer({
					sessionId: '0x0001A2B3',
					round: 0x002a,
					frameType: 'Compute',
					timestamps: 'ToF = 4.7 ns → distance = 1.41 m (±6 cm std)',
					peer: 'DS-TWR cross-product cancels clock drift'
				})
			]
		},
		{
			id: 'ble-result',
			label: 'Result back over BLE — Unlock / Refresh / Stop',
			description:
				"The result is signalled back to the application over the BLE encrypted channel. For {{ccc-digital-key|CCC Digital Key}}, if `distance ≤ threshold` *and* the credential is valid, the car unlocks. For Apple AirTag Precision Finding, the distance (and the PDoA-derived bearing vector from the iPhone's multiple U2 antennas) refreshes at ~10 Hz so the haptic + display can guide the user to the exact spot.",
			fromActor: 'anchor',
			toActor: 'phone',
			duration: 800,
			highlight: ['Channel', 'Mode'],
			data: 'BLE GATT notify: distance=1.41 m, bearing=[+12°, -3°], STS=valid → UNLOCK',
			layers: [
				createUWBPHYLayer({
					channel: '(back to BLE 2.402 GHz — UWB radio off after the ranging round)',
					mode: 'BLE 2M PHY, GATT notify',
					shr: '(BLE LL header)',
					phr: '(L2CAP + ATT framing)',
					psdu: 'GATT notify: distance, bearing vector, status',
					sts: '(none)'
				})
			]
		}
	]
};
