/**
 * Part VI — Async / IoT.
 *
 * Decoupled, message-oriented protocols for sensors, microservices,
 * and event streams.
 */

import type { BookPart } from '../types';

export const asyncIot: BookPart = {
	id: 'async-iot',
	title: 'Async / IoT',
	label: 'VI',
	description: 'Decoupled, message-oriented protocols for sensors, microservices, and event streams.',
	chapters: [
		{
			id: 'mqtt',
			title: 'MQTT',
			synopsis: 'Sensors, satellites, and 2-byte publish overhead.',
			slots: [
				{
					kind: 'prose',
					sections: [
						{
							type: 'narrative',
							title: 'Designed for the Worst Network on Earth',
							text: `[[mqtt|MQTT]] (Message Queuing Telemetry Transport) was invented in 1999 by Andy Stanford-Clark at IBM and Arlen Nipper at Cirrus Link, originally to monitor oil pipelines via satellite. The constraint was brutal: kilobits-per-second satellite links priced per byte, devices that ran for years on a single battery, network drops measured in hours.

The protocol's response was minimalism. The smallest publish frame is **2 bytes of header** plus topic and payload. Three quality-of-service levels (at-most-once, at-least-once, exactly-once) let the application trade reliability for bandwidth. A persistent **session** survives disconnections — when a sleeping sensor wakes up an hour later and reconnects, the broker delivers any messages it missed.

The architecture is **publish-subscribe** through a central **broker**. Sensors publish to topics like \`farm/north/soil-moisture\`; subscribers (a dashboard, an irrigation controller) get every message published to topics matching their subscription. Producers and consumers do not need to know about each other.

MQTT is the de facto IoT protocol. Tesla's vehicles use it to phone home. Ring doorbells, AWS IoT Core, the Matter smart-home standard, Facebook Messenger's mobile push (yes, really) all run on MQTT or its variants.`
						},
						{
							type: 'callout',
							title: '2-byte overhead is not just an engineering preference.',
							text: 'On a satellite link priced at $0.20/KB, every byte saved across millions of devices is real money. MQTT was designed when overhead was not an aesthetic choice but a budget item.'
						}
					]
				},
				{ kind: 'protocol', id: 'mqtt' },
				{ kind: 'simulation', protocolId: 'mqtt' }
			]
		},
		{
			id: 'amqp',
			title: 'AMQP',
			synopsis: 'Enterprise messaging with content-based routing.',
			slots: [
				{
					kind: 'prose',
					sections: [
						{
							type: 'narrative',
							title: 'Wire-Level Banking Plumbing',
							text: `[[amqp|AMQP]] (Advanced Message Queuing Protocol) was started in 2003 by John O'Hara at JPMorgan Chase, who wanted vendor-neutral messaging because IBM MQ Series and TIBCO charged extortionate per-CPU licensing. The 1.0 version was ratified by OASIS in 2011 and became ISO/IEC 19464 in 2014.

Where [[mqtt|MQTT]] is intentionally minimal, AMQP is rich. **Exchanges** route messages to **queues** based on routing keys (direct), patterns (topic), header values (headers), or fanout broadcast. **Durable queues** survive broker restarts. **Transactions** group multiple operations atomically. **Channels** multiplex multiple logical sessions over a single TCP connection. The wire format is a tagged binary protocol with explicit framing.

RabbitMQ (originally an AMQP 0-9-1 implementation) became the most widely deployed AMQP broker. Banks use AMQP for trade messaging, where exactly-once delivery and audit trails are non-negotiable. Microservice architectures use it for command queues and asynchronous task dispatch.

The trade-off versus [[mqtt|MQTT]] is operational complexity. An AMQP broker is a database — you size it, replicate it, monitor it. An MQTT broker is closer to a router — stateless and small. Choose AMQP when transactions matter; choose MQTT when scale and simplicity matter.`
						}
					]
				},
				{ kind: 'protocol', id: 'amqp' },
				{
					kind: 'comparison',
					pairIds: ['mqtt', 'amqp']
				}
			]
		},
		{
			id: 'kafka',
			title: 'Kafka',
			synopsis: 'A distributed commit log as the unit of architecture.',
			slots: [
				{
					kind: 'prose',
					sections: [
						{
							type: 'narrative',
							title: 'The Log Is the Database',
							text: `[[kafka|Apache Kafka]] was open-sourced by LinkedIn in 2011 to handle their activity tracking pipeline — events generated by every page view, search, click, message — at a scale that traditional message brokers could not. The architectural insight, articulated by Jay Kreps in his essay **"The Log: What every software engineer should know about real-time data's unifying abstraction,"** is that **a distributed, append-only log is the right primitive for asynchronous communication at scale**.

A Kafka **topic** is a partitioned log. Producers append records; consumers read them at their own pace, tracking their position by offset. The log is **persistent** — records are not deleted when consumed, they age out by retention policy (often days or weeks). That persistence enables **event sourcing**, **stream processing**, **replay**, and **multiple independent consumer groups** reading the same log for different purposes.

Kafka is designed for **horizontal scale**. Topics are split into partitions distributed across a cluster; each partition is an ordered log replicated across multiple brokers. A single Kafka cluster can handle millions of messages per second per topic, which is two or three orders of magnitude more than [[amqp|AMQP]] or [[mqtt|MQTT]] brokers.

Kafka's protocol is its own (binary, TCP-based, not interoperable with AMQP or MQTT). The trade-off versus a traditional broker: Kafka does not deliver messages to consumers, consumers pull. There is no per-message acknowledgement or routing; the log is the universal contract. That simplicity is what lets it scale.`
						}
					]
				},
				{ kind: 'protocol', id: 'kafka' },
				{ kind: 'simulation', protocolId: 'kafka' }
			]
		},
		{
			id: 'coap',
			title: 'CoAP',
			synopsis: 'REST shrunk for microcontrollers.',
			slots: [
				{
					kind: 'prose',
					sections: [
						{
							type: 'narrative',
							title: 'HTTP at 32 kB of RAM',
							text: `[[coap|CoAP]] (Constrained Application Protocol, RFC 7252, 2014) is what you build when you want REST semantics on a 32 kB microcontroller talking over a 50 kbps mesh radio. It looks like [[http1|HTTP]] from a distance — GET, POST, PUT, DELETE, status codes, URIs — but the wire format is a 4-byte binary header instead of text, and it runs over [[udp|UDP]] instead of [[tcp|TCP]].

The brilliance is the close mapping to HTTP. A [[coap|CoAP]] proxy can transparently translate between CoAP devices and an HTTP-speaking cloud backend. Your IoT mesh can speak CoAP to each other for efficiency, then a single border router exposes the same resources via HTTP to the rest of the world.

CoAP includes **observe** — a long-running subscription where a client says "GET this resource and notify me whenever it changes" — which fills the gap UDP would otherwise leave for live data. It also has **block-wise transfers** for resources too large to fit in a single UDP datagram, and **DTLS** for security (the UDP equivalent of TLS).

CoAP has not displaced [[mqtt|MQTT]] in IoT, mostly because pub/sub is a more useful pattern for sensor networks than request/response. But where you need RESTful resource semantics on a constrained device — Matter (smart-home devices), Thread mesh networks, OMA LwM2M (mobile device management) — CoAP is the answer.`
						}
					]
				},
				{ kind: 'protocol', id: 'coap' },
				{
					kind: 'comparison',
					pairIds: ['mqtt', 'coap']
				}
			]
		}
	]
};
